CREATE TABLE SINGER (
      ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , BIRTH_DATE DATE
    , VERSION int(11)
    , UNIQUE (FIRST_NAME, LAST_NAME)
);

CREATE TABLE ALBUM (
      ID INT NOT NULL AUTO_INCREMENT  PRIMARY KEY
    , SINGER_ID INT NOT NULL
    , TITLE VARCHAR(100) NOT NULL
    , RELEASE_DATE DATE
    , VERSION INT(11)
    , UNIQUE (SINGER_ID, TITLE)
    , CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID)
        REFERENCES SINGER (ID)
);

CREATE TABLE INSTRUMENT(
  INSTRUMENT_ID VARCHAR(20) PRIMARY KEY
);

CREATE TABLE SINGER_INSTRUMENT(
  SINGER_ID INT NOT NULL,
  INSTRUMENT_ID VARCHAR(20) NOT NULL ,
  CONSTRAINT FK_SINGER_INSTRUMENT FOREIGN KEY (SINGER_ID) REFERENCES SINGER(ID),
  CONSTRAINT FK_INSTRUMENT FOREIGN KEY (INSTRUMENT_ID) REFERENCES INSTRUMENT(INSTRUMENT_ID)

);